### ISSUE TITLE
Tick on Server

### ISSUE THREAD

**Issue by AccordsDev** [ConsularAtol/consulars-origins#1]
We came to realize that the mod was constantly checking for pickaxe and stoneling progression even from people that had no interaction with the mod, this caused significant lag issues and increased our tick speed on the server particularly as more people joined the server.

**Comment by ConsularAtol** [comment]
Oh, I actually didn't think about that. Let me fix my sloppy code real quick. I should have a fix within a day or two.

**Comment by AccordsDev** [comment]
That would be amazing, we really really liked the origins they were cool, but it just tanked out server performance.

**Comment by ConsularAtol** [comment]
It has been fixed. Sorry it took longer than I had wanted it to, I was having issues with Java. But a version of the mod with this issue patched should be released in about 10 minutes from me writing this. I will now close this issue.
