### ISSUE TITLE
Please Help With The Crafting Of Items Needed To Evolve

### ISSUE THREAD

**Issue by Assuming132** [ConsularAtol/consulars-origins#2]
Hello i need help for the crafting recipes for the items like coffin and all the golem parts because for some reason the /recipe command isn't working for me, i gave myself the bottom-it worked but the shell and top didnt like give me the recipe, so yeah can you please help?

**Comment by ConsularAtol** [comment]
I'd recommend using a mod like Roughly Enough Items (REI) for modded recipes.

Coffin Recipe is:
(Diamond)(Plank)(Diamond)
(Plank)(Bed)(Plank)
(Diamond)(Plank)(Diamond)

Golem Totem shell is made with a bucket and a netherite ingot in a smithing table.

Golem Totem top is made by putting a Golem Totem Shell in a stonecutter.
