### ISSUE TITLE
No textures?

### ISSUE THREAD

**Issue by theDerxu** [ConsularAtol/consulars-origins#5]
Version: 1.9.0
Mods list: 
![image](https://user-images.githubusercontent.com/88974734/234710622-76642371-3579-4fe9-b910-16981269e51c.png)
Bug: It seems all of the textures for this mod are blank? I am not sure why.
![image](https://user-images.githubusercontent.com/88974734/234710717-be709dab-7ce4-478e-a0cc-ccb158847bf7.png)
Any ideas?

**Comment by ConsularAtol** [comment]
I discovered this during a playthrough of my own. This will be fixed soon.

**Comment by theDerxu** [comment]
Alright, thank you :]

**Comment by ConsularAtol** [comment]
Fixed. will be in the next patch.
