### ISSUE TITLE
Mushling not working as initial origin (Curseforge, Minecraft 1.20.1)

### ISSUE THREAD

**Issue by Klauros** [ConsularAtol/consulars-origins#6]
When I create a new game or join a multiplayer game for the first time and choose the Mushling as my initial origin (which I believe is called mushboi in the code), the game freezes.  If I click escape, the world loads up, but blocks I break do not drop and when I click save and quit the game freezes again and doesn't save.  There isn't a crash or anything like that, minecraft just stays frozen until I force quit it.

I have tested this on mod versions 1.10.0 and 1.10.1 on Curseforge for Minecraft 1.20.1 both with and without mods other than the required ones (origins, pehkui, fabric API)

**Comment by ConsularAtol** [comment]
This is caused by the game taking too long to locate a mushroom fields biome, there's no way for me to fix it without completely changing what biome you spawn in. Eventually, it should unfreeze.
