### ISSUE TITLE
JEI 1.20.1 No Crafting Recipes

### ISSUE THREAD

**Issue by MorganaLaLuna** [ConsularAtol/consulars-origins#7]
As title says, I'm using JEI 1.20.1 and I'm not seeing any crafting recipes from this mod.
Also, due to the lack of documentation (Or extreme difficulty in finding it, as there is none here on GitHub or on Curseforge), I can't find the crafting recipes either.

I would recommend adding JEI compatibility or something and definitely proper documentation.
Even just images of the crafting recipes is better than nothing.

EDIT: The recipe shows up if I press R on the coffin, but I can't see any recipes from your mod in the JEI window
EDIT2: Actually, none of the items from your mod even show up in the creative menu. Without somehow already knowing the recipes, which can't be found unless you have the item already, you basically can't obtain them

**Comment by ConsularAtol** [comment]
Fixed this and forgot to close it oops
